### ISSUE TITLE
Restart crashed due to external B-field

### ISSUE THREAD

**Issue by weipengyao** [SmileiPIC/Smilei#348]
## Description

Checkpoint fails to write the dumped data when applying external B-field.

## Steps to reproduce the problem

To reproduce the problem, I attach the test namelist here.
Without the External_field module, the restart dumps the data fine.
However, with the External_field module, at the `dump_step`, HDF5 will give a series of error messages.

[ckp_externalB.py.txt](https://github.com/SmileiPIC/Smilei/files/5741987/ckp_externalB.py.txt)

## Parameters

`make env` gives:

```
SMILEICXX : mpicxx
PYTHONEXE : python3
MPIVERSION :
VERSION : b'v4.4-784-gc3f8cc8'-b'work'
OPENMP_FLAG : -fopenmp -D_OMP
HDF5_ROOT_DIR : /scinet/niagara/software/2019b/modules/intel-2019u3-intelmpi-2019u3/hdf5/1.10.5
SITEDIR : /home/a/anticipa/weipeng/.local/lib/python3.6/site-packages
PY_CXXFLAGS : -I/scinet/niagara/software/2019b/opt/base/python/3.6.8/include/python3.6m -I/scinet/niagara/software/2019b/opt/base/python/3.6.8/include/python3.6m -I/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/site-packages/numpy/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
PY_LDFLAGS : -lpython3.6m -lpthread -ldl -lutil -lm -Xlinker -export-dynamic
CXXFLAGS : -D__VERSION=\"b'v4.4-784-gc3f8cc8'-b'work'\" -D_VECTO -std=c++11 -Wall  -I/scinet/niagara/software/2019b/modules/intel-2019u3-intelmpi-2019u3/hdf5/1.10.5/include -Isrc -Isrc/Params -Isrc/ElectroMagnSolver -Isrc/ElectroMagn -Isrc/ElectroMagnBC -Isrc/Particles -Isrc/Radiation -Isrc/Ionization -Isrc/Interpolator -Isrc/Collisions -Isrc/Merging -Isrc/Tools -Isrc/Python -Isrc/Projector -Isrc/DomainDecomposition -Isrc/MovWindow -Isrc/Profiles -Isrc/picsar_interface -Isrc/Checkpoint -Isrc/Pusher -Isrc/Field -Isrc/MultiphotonBreitWheeler -Isrc/SmileiMPI -Isrc/Species -Isrc/Diagnostic -Isrc/ParticleInjector -Isrc/Patch -Ibuild/src/Python -I/scinet/niagara/software/2019b/opt/base/python/3.6.8/include/python3.6m -I/scinet/niagara/software/2019b/opt/base/python/3.6.8/include/python3.6m -I/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/site-packages/numpy/core/include -DSMILEI_USE_NUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -O3 -g  -fopenmp -D_OMP
LDFLAGS : -L/scinet/niagara/software/2019b/modules/intel-2019u3-intelmpi-2019u3/hdf5/1.10.5/lib   -lhdf5 -lpython3.6m -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -L/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib -lm -fopenmp -D_OMP
```
## Related error messages and former attempts

I also have a large-scale simulation which I need to use the restart module. 
It gives the same errors #335 , with different versions of HDF5 and SMILEI.
However, when I try to restart from a case in the `benchmarks` folder, it works just fine.
So I started to add modules one-by-one from my simulation into the test case, and finally I found that the external B-field caused this issue.
Then, when I remove the external B-field module from my original large-scale simulation, the restart works fine, too.
Since the external B-field is crucial for the physics I am dealing with, so I can't bypass this.

I don't know if anyone has met with this kind of problems before, any help would be much appreciated.
Thanks in advance.

**Comment by mccoys** [comment]
I have pushed a fix that should work for you. Please confirm.

**Comment by weipengyao** [comment]
> I have pushed a fix that should work for you. Please confirm.

Thanks! I will try that now and keep you updated.

**Comment by weipengyao** [comment]
Dear @mccoys 

With your push, the test case now works fine, thanks again.
I will try the large-scale case to see if anything unexpected appears.

BTW, there's a warning (appears before and still exist now) saying that `[WARNING] Cannot find attribute CommitDate`.
I hope it doesn't matter? Or how can I resolve it?

I will close this issue when I confirm that the large-scale case works fine.

**Comment by mccoys** [comment]
This `CommitDate` is a remain from a very old version. We should remove it altogether as it has absolutely no impact anywhere in the code.

**Comment by weipengyao** [comment]
Thanks for the answer. The large-scale case also works fine! 

I should also mention that after this fix, both `dump_minute` and `dump_step` work fine.

I think this issue has been solved, so I will close it.

Thanks again and all the best to all SMILEI developers and users.
